[[pages]]
path = "streamlit_app.py"
name = "Home"
icon = ":house:"

[[pages]]
path = "pages/1_ğŸ“š_Education.py"

[[pages]]
path = "pages/2_ğŸ“Š_Employment.py"

[[pages]]
path = "pages/3_ğŸ¥_Well-being.py"

[[pages]]
path = "pages/4_â“_Help.py"
